import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import {
  AdminContent,
  AdminSidebar,
  AdminTopbar,
  AdminTopbarMobile,
} from "../components/structures";

const Home: NextPage = () => {
  const [sidebarOpen, setSidebarOpen] = useState(false);
  return (
    <div className="bg-wp-background min-h-screen">
      <Head>
        <title>
          NextPress - A WordPress-inspired dashboard built with Next.js
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AdminTopbar />
      <AdminSidebar sidebarOpen={sidebarOpen} setSidebarOpen={setSidebarOpen} />
      <div className="md:pl-40 flex flex-col flex-1">
        <AdminTopbarMobile callback={() => setSidebarOpen(true)} />
        <AdminContent />
      </div>
    </div>
  );
};

export default Home;
