import type { NextPage } from "next";
import Head from "next/head";
import WPLayout from "../components/structures/WPLayout/WPLayout";

const Home: NextPage = () => {
  return (
    <div className="bg-wp-background min-h-screen">
      <Head>
        <title>
          NextPress - A WordPress-inspired dashboard built with Next.js
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <WPLayout />
    </div>
  );
};

export default Home;
